#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tempora
Version  : 2.1.0
Release  : 21
URL      : https://files.pythonhosted.org/packages/f7/6c/0220713d15e60a607bc72c3025e073308fced307f678c6eeec820ad26b46/tempora-2.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f7/6c/0220713d15e60a607bc72c3025e073308fced307f678c6eeec820ad26b46/tempora-2.1.0.tar.gz
Summary  : Objects and routines pertaining to date and time (tempora)
Group    : Development/Tools
License  : MIT
Requires: tempora-bin = %{version}-%{release}
Requires: tempora-license = %{version}-%{release}
Requires: tempora-python = %{version}-%{release}
Requires: tempora-python3 = %{version}-%{release}
Requires: jaraco.functools
Requires: pytz
BuildRequires : buildreq-distutils3
BuildRequires : jaraco.functools
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytz
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/tempora.svg
   :target: https://pypi.org/project/tempora

.. image:: https://img.shields.io/pypi/pyversions/tempora.svg

.. image:: https://dev.azure.com/jaraco/tempora/_apis/build/status/jaraco.tempora?branchName=master
   :target: https://dev.azure.com/jaraco/tempora/_build/latest?definitionId=1&branchName=master

.. image:: https://img.shields.io/travis/jaraco/tempora/master.svg
   :target: https://travis-ci.org/jaraco/tempora

.. image:: https://img.shields.io/badge/code%20style-black-000000.svg
   :target: https://github.com/psf/black
   :alt: Code style: Black

.. .. image:: https://img.shields.io/appveyor/ci/jaraco/tempora/master.svg
..    :target: https://ci.appveyor.com/project/jaraco/tempora/branch/master

.. image:: https://readthedocs.org/projects/tempora/badge/?version=latest
   :target: https://tempora.readthedocs.io/en/latest/?badge=latest

Objects and routines pertaining to date and time (tempora).

Modules include:

- tempora (top level package module) contains miscellaneous
   utilities and constants.
- timing contains routines for measuring and profiling.
- schedule contains an event scheduler.
- utc contains routines for getting datetime-aware UTC values
  (Python 3 only).

%package bin
Summary: bin components for the tempora package.
Group: Binaries
Requires: tempora-license = %{version}-%{release}

%description bin
bin components for the tempora package.


%package license
Summary: license components for the tempora package.
Group: Default

%description license
license components for the tempora package.


%package python
Summary: python components for the tempora package.
Group: Default
Requires: tempora-python3 = %{version}-%{release}

%description python
python components for the tempora package.


%package python3
Summary: python3 components for the tempora package.
Group: Default
Requires: python3-core
Provides: pypi(tempora)

%description python3
python3 components for the tempora package.


%prep
%setup -q -n tempora-2.1.0
cd %{_builddir}/tempora-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582912879
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tempora
cp %{_builddir}/tempora-2.1.0/LICENSE %{buildroot}/usr/share/package-licenses/tempora/a1474494d96f6ddb3a9a0d767a09871ffc388faf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/calc-prorate

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tempora/a1474494d96f6ddb3a9a0d767a09871ffc388faf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
